loglevel: Debug
write-directory: output
services:
  myStorageAccount:
    raid: ABS
    tactics:
      - tlp_red
      # - tlp_amber
      # - tlp_green
      # - tlp_clear
    vars:
      storageAccountResourceId: 
