loglevel: Debug
write-directory: output
services:
  myStorageAccount:
    plugin: ABS
    test-suites:
      - tlp_red
      # - tlp_amber
      # - tlp_green
      # - tlp_clear
    vars:
      storageAccountResourceId:
      allowedRegions: []
